package com.crazyclub.www.waterlab.model.mybatis;

import java.util.ArrayList;
import java.util.List;

public class CheckTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public CheckTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCheckTypeIdIsNull() {
            addCriterion("check_type_id is null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdIsNotNull() {
            addCriterion("check_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdEqualTo(Integer value) {
            addCriterion("check_type_id =", value, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdNotEqualTo(Integer value) {
            addCriterion("check_type_id <>", value, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdGreaterThan(Integer value) {
            addCriterion("check_type_id >", value, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_type_id >=", value, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdLessThan(Integer value) {
            addCriterion("check_type_id <", value, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("check_type_id <=", value, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdIn(List<Integer> values) {
            addCriterion("check_type_id in", values, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdNotIn(List<Integer> values) {
            addCriterion("check_type_id not in", values, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("check_type_id between", value1, value2, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("check_type_id not between", value1, value2, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameIsNull() {
            addCriterion("check_type_name is null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameIsNotNull() {
            addCriterion("check_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameEqualTo(String value) {
            addCriterion("check_type_name =", value, "checkTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameNotEqualTo(String value) {
            addCriterion("check_type_name <>", value, "checkTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameGreaterThan(String value) {
            addCriterion("check_type_name >", value, "checkTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("check_type_name >=", value, "checkTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameLessThan(String value) {
            addCriterion("check_type_name <", value, "checkTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameLessThanOrEqualTo(String value) {
            addCriterion("check_type_name <=", value, "checkTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameLike(String value) {
            addCriterion("check_type_name like", value, "checkTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameNotLike(String value) {
            addCriterion("check_type_name not like", value, "checkTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameIn(List<String> values) {
            addCriterion("check_type_name in", values, "checkTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameNotIn(List<String> values) {
            addCriterion("check_type_name not in", values, "checkTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameBetween(String value1, String value2) {
            addCriterion("check_type_name between", value1, value2, "checkTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameNotBetween(String value1, String value2) {
            addCriterion("check_type_name not between", value1, value2, "checkTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelIsNull() {
            addCriterion("check_type_label is null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelIsNotNull() {
            addCriterion("check_type_label is not null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelEqualTo(String value) {
            addCriterion("check_type_label =", value, "checkTypeLabel");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelNotEqualTo(String value) {
            addCriterion("check_type_label <>", value, "checkTypeLabel");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelGreaterThan(String value) {
            addCriterion("check_type_label >", value, "checkTypeLabel");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelGreaterThanOrEqualTo(String value) {
            addCriterion("check_type_label >=", value, "checkTypeLabel");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelLessThan(String value) {
            addCriterion("check_type_label <", value, "checkTypeLabel");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelLessThanOrEqualTo(String value) {
            addCriterion("check_type_label <=", value, "checkTypeLabel");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelLike(String value) {
            addCriterion("check_type_label like", value, "checkTypeLabel");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelNotLike(String value) {
            addCriterion("check_type_label not like", value, "checkTypeLabel");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelIn(List<String> values) {
            addCriterion("check_type_label in", values, "checkTypeLabel");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelNotIn(List<String> values) {
            addCriterion("check_type_label not in", values, "checkTypeLabel");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelBetween(String value1, String value2) {
            addCriterion("check_type_label between", value1, value2, "checkTypeLabel");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelNotBetween(String value1, String value2) {
            addCriterion("check_type_label not between", value1, value2, "checkTypeLabel");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitIsNull() {
            addCriterion("check_type_unit is null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitIsNotNull() {
            addCriterion("check_type_unit is not null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitEqualTo(String value) {
            addCriterion("check_type_unit =", value, "checkTypeUnit");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitNotEqualTo(String value) {
            addCriterion("check_type_unit <>", value, "checkTypeUnit");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitGreaterThan(String value) {
            addCriterion("check_type_unit >", value, "checkTypeUnit");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitGreaterThanOrEqualTo(String value) {
            addCriterion("check_type_unit >=", value, "checkTypeUnit");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitLessThan(String value) {
            addCriterion("check_type_unit <", value, "checkTypeUnit");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitLessThanOrEqualTo(String value) {
            addCriterion("check_type_unit <=", value, "checkTypeUnit");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitLike(String value) {
            addCriterion("check_type_unit like", value, "checkTypeUnit");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitNotLike(String value) {
            addCriterion("check_type_unit not like", value, "checkTypeUnit");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitIn(List<String> values) {
            addCriterion("check_type_unit in", values, "checkTypeUnit");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitNotIn(List<String> values) {
            addCriterion("check_type_unit not in", values, "checkTypeUnit");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitBetween(String value1, String value2) {
            addCriterion("check_type_unit between", value1, value2, "checkTypeUnit");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitNotBetween(String value1, String value2) {
            addCriterion("check_type_unit not between", value1, value2, "checkTypeUnit");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionIsNull() {
            addCriterion("check_type_description is null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionIsNotNull() {
            addCriterion("check_type_description is not null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionEqualTo(String value) {
            addCriterion("check_type_description =", value, "checkTypeDescription");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionNotEqualTo(String value) {
            addCriterion("check_type_description <>", value, "checkTypeDescription");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionGreaterThan(String value) {
            addCriterion("check_type_description >", value, "checkTypeDescription");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("check_type_description >=", value, "checkTypeDescription");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionLessThan(String value) {
            addCriterion("check_type_description <", value, "checkTypeDescription");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionLessThanOrEqualTo(String value) {
            addCriterion("check_type_description <=", value, "checkTypeDescription");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionLike(String value) {
            addCriterion("check_type_description like", value, "checkTypeDescription");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionNotLike(String value) {
            addCriterion("check_type_description not like", value, "checkTypeDescription");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionIn(List<String> values) {
            addCriterion("check_type_description in", values, "checkTypeDescription");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionNotIn(List<String> values) {
            addCriterion("check_type_description not in", values, "checkTypeDescription");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionBetween(String value1, String value2) {
            addCriterion("check_type_description between", value1, value2, "checkTypeDescription");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionNotBetween(String value1, String value2) {
            addCriterion("check_type_description not between", value1, value2, "checkTypeDescription");
            return (Criteria) this;
        }

        public Criteria andCheckTypeNameLikeInsensitive(String value) {
            addCriterion("upper(check_type_name) like", value.toUpperCase(), "checkTypeName");
            return (Criteria) this;
        }

        public Criteria andCheckTypeLabelLikeInsensitive(String value) {
            addCriterion("upper(check_type_label) like", value.toUpperCase(), "checkTypeLabel");
            return (Criteria) this;
        }

        public Criteria andCheckTypeUnitLikeInsensitive(String value) {
            addCriterion("upper(check_type_unit) like", value.toUpperCase(), "checkTypeUnit");
            return (Criteria) this;
        }

        public Criteria andCheckTypeDescriptionLikeInsensitive(String value) {
            addCriterion("upper(check_type_description) like", value.toUpperCase(), "checkTypeDescription");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_check_type
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 27 18:07:00 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}