package com.crazyclub.www.waterlab.model.mybatis;

import java.io.Serializable;

public class CheckType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_check_type.check_type_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Integer checkTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_check_type.check_type_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String checkTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_check_type.check_type_label
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String checkTypeLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_check_type.check_type_unit
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String checkTypeUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_check_type.check_type_description
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String checkTypeDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_check_type.check_type_id
     *
     * @return the value of wl_base_check_type.check_type_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Integer getCheckTypeId() {
        return checkTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_check_type.check_type_id
     *
     * @param checkTypeId the value for wl_base_check_type.check_type_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setCheckTypeId(Integer checkTypeId) {
        this.checkTypeId = checkTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_check_type.check_type_name
     *
     * @return the value of wl_base_check_type.check_type_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getCheckTypeName() {
        return checkTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_check_type.check_type_name
     *
     * @param checkTypeName the value for wl_base_check_type.check_type_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setCheckTypeName(String checkTypeName) {
        this.checkTypeName = checkTypeName == null ? null : checkTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_check_type.check_type_label
     *
     * @return the value of wl_base_check_type.check_type_label
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getCheckTypeLabel() {
        return checkTypeLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_check_type.check_type_label
     *
     * @param checkTypeLabel the value for wl_base_check_type.check_type_label
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setCheckTypeLabel(String checkTypeLabel) {
        this.checkTypeLabel = checkTypeLabel == null ? null : checkTypeLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_check_type.check_type_unit
     *
     * @return the value of wl_base_check_type.check_type_unit
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getCheckTypeUnit() {
        return checkTypeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_check_type.check_type_unit
     *
     * @param checkTypeUnit the value for wl_base_check_type.check_type_unit
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setCheckTypeUnit(String checkTypeUnit) {
        this.checkTypeUnit = checkTypeUnit == null ? null : checkTypeUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_check_type.check_type_description
     *
     * @return the value of wl_base_check_type.check_type_description
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getCheckTypeDescription() {
        return checkTypeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_check_type.check_type_description
     *
     * @param checkTypeDescription the value for wl_base_check_type.check_type_description
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setCheckTypeDescription(String checkTypeDescription) {
        this.checkTypeDescription = checkTypeDescription == null ? null : checkTypeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CheckType other = (CheckType) that;
        return (this.getCheckTypeId() == null ? other.getCheckTypeId() == null : this.getCheckTypeId().equals(other.getCheckTypeId()))
            && (this.getCheckTypeName() == null ? other.getCheckTypeName() == null : this.getCheckTypeName().equals(other.getCheckTypeName()))
            && (this.getCheckTypeLabel() == null ? other.getCheckTypeLabel() == null : this.getCheckTypeLabel().equals(other.getCheckTypeLabel()))
            && (this.getCheckTypeUnit() == null ? other.getCheckTypeUnit() == null : this.getCheckTypeUnit().equals(other.getCheckTypeUnit()))
            && (this.getCheckTypeDescription() == null ? other.getCheckTypeDescription() == null : this.getCheckTypeDescription().equals(other.getCheckTypeDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCheckTypeId() == null) ? 0 : getCheckTypeId().hashCode());
        result = prime * result + ((getCheckTypeName() == null) ? 0 : getCheckTypeName().hashCode());
        result = prime * result + ((getCheckTypeLabel() == null) ? 0 : getCheckTypeLabel().hashCode());
        result = prime * result + ((getCheckTypeUnit() == null) ? 0 : getCheckTypeUnit().hashCode());
        result = prime * result + ((getCheckTypeDescription() == null) ? 0 : getCheckTypeDescription().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_check_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", checkTypeId=").append(checkTypeId);
        sb.append(", checkTypeName=").append(checkTypeName);
        sb.append(", checkTypeLabel=").append(checkTypeLabel);
        sb.append(", checkTypeUnit=").append(checkTypeUnit);
        sb.append(", checkTypeDescription=").append(checkTypeDescription);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}