package com.crazyclub.www.waterlab.model.mybatis;

import java.io.Serializable;

public class CheckPoint implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_checkpoint.checkpoint_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String checkpointId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_checkpoint.checkpoint_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String checkpointName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_checkpoint.checkpoint_label
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String checkpointLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_checkpoint.checkpoint_longitude
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Double checkpointLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_checkpoint.checkpoint_water_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Integer checkpointWaterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_checkpoint.checkpoint_latitude
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Double checkpointLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_checkpoint
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_checkpoint.checkpoint_id
     *
     * @return the value of wl_base_checkpoint.checkpoint_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getCheckpointId() {
        return checkpointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_checkpoint.checkpoint_id
     *
     * @param checkpointId the value for wl_base_checkpoint.checkpoint_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setCheckpointId(String checkpointId) {
        this.checkpointId = checkpointId == null ? null : checkpointId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_checkpoint.checkpoint_name
     *
     * @return the value of wl_base_checkpoint.checkpoint_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getCheckpointName() {
        return checkpointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_checkpoint.checkpoint_name
     *
     * @param checkpointName the value for wl_base_checkpoint.checkpoint_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setCheckpointName(String checkpointName) {
        this.checkpointName = checkpointName == null ? null : checkpointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_checkpoint.checkpoint_label
     *
     * @return the value of wl_base_checkpoint.checkpoint_label
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getCheckpointLabel() {
        return checkpointLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_checkpoint.checkpoint_label
     *
     * @param checkpointLabel the value for wl_base_checkpoint.checkpoint_label
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setCheckpointLabel(String checkpointLabel) {
        this.checkpointLabel = checkpointLabel == null ? null : checkpointLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_checkpoint.checkpoint_longitude
     *
     * @return the value of wl_base_checkpoint.checkpoint_longitude
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Double getCheckpointLongitude() {
        return checkpointLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_checkpoint.checkpoint_longitude
     *
     * @param checkpointLongitude the value for wl_base_checkpoint.checkpoint_longitude
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setCheckpointLongitude(Double checkpointLongitude) {
        this.checkpointLongitude = checkpointLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_checkpoint.checkpoint_water_id
     *
     * @return the value of wl_base_checkpoint.checkpoint_water_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Integer getCheckpointWaterId() {
        return checkpointWaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_checkpoint.checkpoint_water_id
     *
     * @param checkpointWaterId the value for wl_base_checkpoint.checkpoint_water_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setCheckpointWaterId(Integer checkpointWaterId) {
        this.checkpointWaterId = checkpointWaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_checkpoint.checkpoint_latitude
     *
     * @return the value of wl_base_checkpoint.checkpoint_latitude
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Double getCheckpointLatitude() {
        return checkpointLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_checkpoint.checkpoint_latitude
     *
     * @param checkpointLatitude the value for wl_base_checkpoint.checkpoint_latitude
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setCheckpointLatitude(Double checkpointLatitude) {
        this.checkpointLatitude = checkpointLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_checkpoint
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CheckPoint other = (CheckPoint) that;
        return (this.getCheckpointId() == null ? other.getCheckpointId() == null : this.getCheckpointId().equals(other.getCheckpointId()))
            && (this.getCheckpointName() == null ? other.getCheckpointName() == null : this.getCheckpointName().equals(other.getCheckpointName()))
            && (this.getCheckpointLabel() == null ? other.getCheckpointLabel() == null : this.getCheckpointLabel().equals(other.getCheckpointLabel()))
            && (this.getCheckpointLongitude() == null ? other.getCheckpointLongitude() == null : this.getCheckpointLongitude().equals(other.getCheckpointLongitude()))
            && (this.getCheckpointWaterId() == null ? other.getCheckpointWaterId() == null : this.getCheckpointWaterId().equals(other.getCheckpointWaterId()))
            && (this.getCheckpointLatitude() == null ? other.getCheckpointLatitude() == null : this.getCheckpointLatitude().equals(other.getCheckpointLatitude()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_checkpoint
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCheckpointId() == null) ? 0 : getCheckpointId().hashCode());
        result = prime * result + ((getCheckpointName() == null) ? 0 : getCheckpointName().hashCode());
        result = prime * result + ((getCheckpointLabel() == null) ? 0 : getCheckpointLabel().hashCode());
        result = prime * result + ((getCheckpointLongitude() == null) ? 0 : getCheckpointLongitude().hashCode());
        result = prime * result + ((getCheckpointWaterId() == null) ? 0 : getCheckpointWaterId().hashCode());
        result = prime * result + ((getCheckpointLatitude() == null) ? 0 : getCheckpointLatitude().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_checkpoint
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", checkpointId=").append(checkpointId);
        sb.append(", checkpointName=").append(checkpointName);
        sb.append(", checkpointLabel=").append(checkpointLabel);
        sb.append(", checkpointLongitude=").append(checkpointLongitude);
        sb.append(", checkpointWaterId=").append(checkpointWaterId);
        sb.append(", checkpointLatitude=").append(checkpointLatitude);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}