package com.crazyclub.www.waterlab.model.mybatis;

import java.io.Serializable;

public class Department implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_department.department_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_department.department_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_department.department_label
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String departmentLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_department.department_description
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String departmentDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_department
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_department.department_id
     *
     * @return the value of wl_base_department.department_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_department.department_id
     *
     * @param departmentId the value for wl_base_department.department_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_department.department_name
     *
     * @return the value of wl_base_department.department_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_department.department_name
     *
     * @param departmentName the value for wl_base_department.department_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_department.department_label
     *
     * @return the value of wl_base_department.department_label
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getDepartmentLabel() {
        return departmentLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_department.department_label
     *
     * @param departmentLabel the value for wl_base_department.department_label
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setDepartmentLabel(String departmentLabel) {
        this.departmentLabel = departmentLabel == null ? null : departmentLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_department.department_description
     *
     * @return the value of wl_base_department.department_description
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getDepartmentDescription() {
        return departmentDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_department.department_description
     *
     * @param departmentDescription the value for wl_base_department.department_description
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setDepartmentDescription(String departmentDescription) {
        this.departmentDescription = departmentDescription == null ? null : departmentDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_department
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Department other = (Department) that;
        return (this.getDepartmentId() == null ? other.getDepartmentId() == null : this.getDepartmentId().equals(other.getDepartmentId()))
            && (this.getDepartmentName() == null ? other.getDepartmentName() == null : this.getDepartmentName().equals(other.getDepartmentName()))
            && (this.getDepartmentLabel() == null ? other.getDepartmentLabel() == null : this.getDepartmentLabel().equals(other.getDepartmentLabel()))
            && (this.getDepartmentDescription() == null ? other.getDepartmentDescription() == null : this.getDepartmentDescription().equals(other.getDepartmentDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_department
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDepartmentId() == null) ? 0 : getDepartmentId().hashCode());
        result = prime * result + ((getDepartmentName() == null) ? 0 : getDepartmentName().hashCode());
        result = prime * result + ((getDepartmentLabel() == null) ? 0 : getDepartmentLabel().hashCode());
        result = prime * result + ((getDepartmentDescription() == null) ? 0 : getDepartmentDescription().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_department
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", departmentId=").append(departmentId);
        sb.append(", departmentName=").append(departmentName);
        sb.append(", departmentLabel=").append(departmentLabel);
        sb.append(", departmentDescription=").append(departmentDescription);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}