package com.crazyclub.www.waterlab.model.mybatis;

import java.io.Serializable;

public class Permission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_permission.permission_id
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_permission.permission_name
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_permission.permission_description
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private String permissionDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_permission.permission_admin
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private String permissionAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_permission.permission_type_id
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private Integer permissionTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_permission.permission_pid
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private Integer permissionPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_permission.permission_id
     *
     * @return the value of wl_base_permission.permission_id
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_permission.permission_id
     *
     * @param permissionId the value for wl_base_permission.permission_id
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_permission.permission_name
     *
     * @return the value of wl_base_permission.permission_name
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_permission.permission_name
     *
     * @param permissionName the value for wl_base_permission.permission_name
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_permission.permission_description
     *
     * @return the value of wl_base_permission.permission_description
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public String getPermissionDescription() {
        return permissionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_permission.permission_description
     *
     * @param permissionDescription the value for wl_base_permission.permission_description
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setPermissionDescription(String permissionDescription) {
        this.permissionDescription = permissionDescription == null ? null : permissionDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_permission.permission_admin
     *
     * @return the value of wl_base_permission.permission_admin
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public String getPermissionAdmin() {
        return permissionAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_permission.permission_admin
     *
     * @param permissionAdmin the value for wl_base_permission.permission_admin
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setPermissionAdmin(String permissionAdmin) {
        this.permissionAdmin = permissionAdmin == null ? null : permissionAdmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_permission.permission_type_id
     *
     * @return the value of wl_base_permission.permission_type_id
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public Integer getPermissionTypeId() {
        return permissionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_permission.permission_type_id
     *
     * @param permissionTypeId the value for wl_base_permission.permission_type_id
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setPermissionTypeId(Integer permissionTypeId) {
        this.permissionTypeId = permissionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_permission.permission_pid
     *
     * @return the value of wl_base_permission.permission_pid
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public Integer getPermissionPid() {
        return permissionPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_permission.permission_pid
     *
     * @param permissionPid the value for wl_base_permission.permission_pid
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setPermissionPid(Integer permissionPid) {
        this.permissionPid = permissionPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Permission other = (Permission) that;
        return (this.getPermissionId() == null ? other.getPermissionId() == null : this.getPermissionId().equals(other.getPermissionId()))
            && (this.getPermissionName() == null ? other.getPermissionName() == null : this.getPermissionName().equals(other.getPermissionName()))
            && (this.getPermissionDescription() == null ? other.getPermissionDescription() == null : this.getPermissionDescription().equals(other.getPermissionDescription()))
            && (this.getPermissionAdmin() == null ? other.getPermissionAdmin() == null : this.getPermissionAdmin().equals(other.getPermissionAdmin()))
            && (this.getPermissionTypeId() == null ? other.getPermissionTypeId() == null : this.getPermissionTypeId().equals(other.getPermissionTypeId()))
            && (this.getPermissionPid() == null ? other.getPermissionPid() == null : this.getPermissionPid().equals(other.getPermissionPid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPermissionId() == null) ? 0 : getPermissionId().hashCode());
        result = prime * result + ((getPermissionName() == null) ? 0 : getPermissionName().hashCode());
        result = prime * result + ((getPermissionDescription() == null) ? 0 : getPermissionDescription().hashCode());
        result = prime * result + ((getPermissionAdmin() == null) ? 0 : getPermissionAdmin().hashCode());
        result = prime * result + ((getPermissionTypeId() == null) ? 0 : getPermissionTypeId().hashCode());
        result = prime * result + ((getPermissionPid() == null) ? 0 : getPermissionPid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", permissionId=").append(permissionId);
        sb.append(", permissionName=").append(permissionName);
        sb.append(", permissionDescription=").append(permissionDescription);
        sb.append(", permissionAdmin=").append(permissionAdmin);
        sb.append(", permissionTypeId=").append(permissionTypeId);
        sb.append(", permissionPid=").append(permissionPid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}