package com.crazyclub.www.waterlab.model.mybatis;

import java.util.ArrayList;
import java.util.List;

public class PermissionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public PermissionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPermissionIdIsNull() {
            addCriterion("permission_id is null");
            return (Criteria) this;
        }

        public Criteria andPermissionIdIsNotNull() {
            addCriterion("permission_id is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionIdEqualTo(Integer value) {
            addCriterion("permission_id =", value, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdNotEqualTo(Integer value) {
            addCriterion("permission_id <>", value, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdGreaterThan(Integer value) {
            addCriterion("permission_id >", value, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("permission_id >=", value, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdLessThan(Integer value) {
            addCriterion("permission_id <", value, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdLessThanOrEqualTo(Integer value) {
            addCriterion("permission_id <=", value, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdIn(List<Integer> values) {
            addCriterion("permission_id in", values, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdNotIn(List<Integer> values) {
            addCriterion("permission_id not in", values, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdBetween(Integer value1, Integer value2) {
            addCriterion("permission_id between", value1, value2, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("permission_id not between", value1, value2, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionNameIsNull() {
            addCriterion("permission_name is null");
            return (Criteria) this;
        }

        public Criteria andPermissionNameIsNotNull() {
            addCriterion("permission_name is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionNameEqualTo(String value) {
            addCriterion("permission_name =", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameNotEqualTo(String value) {
            addCriterion("permission_name <>", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameGreaterThan(String value) {
            addCriterion("permission_name >", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameGreaterThanOrEqualTo(String value) {
            addCriterion("permission_name >=", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameLessThan(String value) {
            addCriterion("permission_name <", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameLessThanOrEqualTo(String value) {
            addCriterion("permission_name <=", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameLike(String value) {
            addCriterion("permission_name like", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameNotLike(String value) {
            addCriterion("permission_name not like", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameIn(List<String> values) {
            addCriterion("permission_name in", values, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameNotIn(List<String> values) {
            addCriterion("permission_name not in", values, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameBetween(String value1, String value2) {
            addCriterion("permission_name between", value1, value2, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameNotBetween(String value1, String value2) {
            addCriterion("permission_name not between", value1, value2, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionIsNull() {
            addCriterion("permission_description is null");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionIsNotNull() {
            addCriterion("permission_description is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionEqualTo(String value) {
            addCriterion("permission_description =", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionNotEqualTo(String value) {
            addCriterion("permission_description <>", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionGreaterThan(String value) {
            addCriterion("permission_description >", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("permission_description >=", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionLessThan(String value) {
            addCriterion("permission_description <", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionLessThanOrEqualTo(String value) {
            addCriterion("permission_description <=", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionLike(String value) {
            addCriterion("permission_description like", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionNotLike(String value) {
            addCriterion("permission_description not like", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionIn(List<String> values) {
            addCriterion("permission_description in", values, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionNotIn(List<String> values) {
            addCriterion("permission_description not in", values, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionBetween(String value1, String value2) {
            addCriterion("permission_description between", value1, value2, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionNotBetween(String value1, String value2) {
            addCriterion("permission_description not between", value1, value2, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminIsNull() {
            addCriterion("permission_admin is null");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminIsNotNull() {
            addCriterion("permission_admin is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminEqualTo(String value) {
            addCriterion("permission_admin =", value, "permissionAdmin");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminNotEqualTo(String value) {
            addCriterion("permission_admin <>", value, "permissionAdmin");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminGreaterThan(String value) {
            addCriterion("permission_admin >", value, "permissionAdmin");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminGreaterThanOrEqualTo(String value) {
            addCriterion("permission_admin >=", value, "permissionAdmin");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminLessThan(String value) {
            addCriterion("permission_admin <", value, "permissionAdmin");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminLessThanOrEqualTo(String value) {
            addCriterion("permission_admin <=", value, "permissionAdmin");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminLike(String value) {
            addCriterion("permission_admin like", value, "permissionAdmin");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminNotLike(String value) {
            addCriterion("permission_admin not like", value, "permissionAdmin");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminIn(List<String> values) {
            addCriterion("permission_admin in", values, "permissionAdmin");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminNotIn(List<String> values) {
            addCriterion("permission_admin not in", values, "permissionAdmin");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminBetween(String value1, String value2) {
            addCriterion("permission_admin between", value1, value2, "permissionAdmin");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminNotBetween(String value1, String value2) {
            addCriterion("permission_admin not between", value1, value2, "permissionAdmin");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIdIsNull() {
            addCriterion("permission_type_id is null");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIdIsNotNull() {
            addCriterion("permission_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIdEqualTo(Integer value) {
            addCriterion("permission_type_id =", value, "permissionTypeId");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIdNotEqualTo(Integer value) {
            addCriterion("permission_type_id <>", value, "permissionTypeId");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIdGreaterThan(Integer value) {
            addCriterion("permission_type_id >", value, "permissionTypeId");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("permission_type_id >=", value, "permissionTypeId");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIdLessThan(Integer value) {
            addCriterion("permission_type_id <", value, "permissionTypeId");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("permission_type_id <=", value, "permissionTypeId");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIdIn(List<Integer> values) {
            addCriterion("permission_type_id in", values, "permissionTypeId");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIdNotIn(List<Integer> values) {
            addCriterion("permission_type_id not in", values, "permissionTypeId");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("permission_type_id between", value1, value2, "permissionTypeId");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("permission_type_id not between", value1, value2, "permissionTypeId");
            return (Criteria) this;
        }

        public Criteria andPermissionPidIsNull() {
            addCriterion("permission_pid is null");
            return (Criteria) this;
        }

        public Criteria andPermissionPidIsNotNull() {
            addCriterion("permission_pid is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionPidEqualTo(Integer value) {
            addCriterion("permission_pid =", value, "permissionPid");
            return (Criteria) this;
        }

        public Criteria andPermissionPidNotEqualTo(Integer value) {
            addCriterion("permission_pid <>", value, "permissionPid");
            return (Criteria) this;
        }

        public Criteria andPermissionPidGreaterThan(Integer value) {
            addCriterion("permission_pid >", value, "permissionPid");
            return (Criteria) this;
        }

        public Criteria andPermissionPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("permission_pid >=", value, "permissionPid");
            return (Criteria) this;
        }

        public Criteria andPermissionPidLessThan(Integer value) {
            addCriterion("permission_pid <", value, "permissionPid");
            return (Criteria) this;
        }

        public Criteria andPermissionPidLessThanOrEqualTo(Integer value) {
            addCriterion("permission_pid <=", value, "permissionPid");
            return (Criteria) this;
        }

        public Criteria andPermissionPidIn(List<Integer> values) {
            addCriterion("permission_pid in", values, "permissionPid");
            return (Criteria) this;
        }

        public Criteria andPermissionPidNotIn(List<Integer> values) {
            addCriterion("permission_pid not in", values, "permissionPid");
            return (Criteria) this;
        }

        public Criteria andPermissionPidBetween(Integer value1, Integer value2) {
            addCriterion("permission_pid between", value1, value2, "permissionPid");
            return (Criteria) this;
        }

        public Criteria andPermissionPidNotBetween(Integer value1, Integer value2) {
            addCriterion("permission_pid not between", value1, value2, "permissionPid");
            return (Criteria) this;
        }

        public Criteria andPermissionNameLikeInsensitive(String value) {
            addCriterion("upper(permission_name) like", value.toUpperCase(), "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionLikeInsensitive(String value) {
            addCriterion("upper(permission_description) like", value.toUpperCase(), "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionAdminLikeInsensitive(String value) {
            addCriterion("upper(permission_admin) like", value.toUpperCase(), "permissionAdmin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_permission
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 06 15:14:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_permission
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}