package com.crazyclub.www.waterlab.model.mybatis;

import java.util.ArrayList;
import java.util.List;

public class RiverOwnerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public RiverOwnerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOwnerIdIsNull() {
            addCriterion("owner_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNotNull() {
            addCriterion("owner_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdEqualTo(Integer value) {
            addCriterion("owner_id =", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotEqualTo(Integer value) {
            addCriterion("owner_id <>", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThan(Integer value) {
            addCriterion("owner_id >", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("owner_id >=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThan(Integer value) {
            addCriterion("owner_id <", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThanOrEqualTo(Integer value) {
            addCriterion("owner_id <=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIn(List<Integer> values) {
            addCriterion("owner_id in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotIn(List<Integer> values) {
            addCriterion("owner_id not in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdBetween(Integer value1, Integer value2) {
            addCriterion("owner_id between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("owner_id not between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIsNull() {
            addCriterion("owner_name is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIsNotNull() {
            addCriterion("owner_name is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNameEqualTo(String value) {
            addCriterion("owner_name =", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotEqualTo(String value) {
            addCriterion("owner_name <>", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameGreaterThan(String value) {
            addCriterion("owner_name >", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameGreaterThanOrEqualTo(String value) {
            addCriterion("owner_name >=", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLessThan(String value) {
            addCriterion("owner_name <", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLessThanOrEqualTo(String value) {
            addCriterion("owner_name <=", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLike(String value) {
            addCriterion("owner_name like", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotLike(String value) {
            addCriterion("owner_name not like", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIn(List<String> values) {
            addCriterion("owner_name in", values, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotIn(List<String> values) {
            addCriterion("owner_name not in", values, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameBetween(String value1, String value2) {
            addCriterion("owner_name between", value1, value2, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotBetween(String value1, String value2) {
            addCriterion("owner_name not between", value1, value2, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionIsNull() {
            addCriterion("owner_position is null");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionIsNotNull() {
            addCriterion("owner_position is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionEqualTo(String value) {
            addCriterion("owner_position =", value, "ownerPosition");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionNotEqualTo(String value) {
            addCriterion("owner_position <>", value, "ownerPosition");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionGreaterThan(String value) {
            addCriterion("owner_position >", value, "ownerPosition");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionGreaterThanOrEqualTo(String value) {
            addCriterion("owner_position >=", value, "ownerPosition");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionLessThan(String value) {
            addCriterion("owner_position <", value, "ownerPosition");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionLessThanOrEqualTo(String value) {
            addCriterion("owner_position <=", value, "ownerPosition");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionLike(String value) {
            addCriterion("owner_position like", value, "ownerPosition");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionNotLike(String value) {
            addCriterion("owner_position not like", value, "ownerPosition");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionIn(List<String> values) {
            addCriterion("owner_position in", values, "ownerPosition");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionNotIn(List<String> values) {
            addCriterion("owner_position not in", values, "ownerPosition");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionBetween(String value1, String value2) {
            addCriterion("owner_position between", value1, value2, "ownerPosition");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionNotBetween(String value1, String value2) {
            addCriterion("owner_position not between", value1, value2, "ownerPosition");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionIsNull() {
            addCriterion("owner_description is null");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionIsNotNull() {
            addCriterion("owner_description is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionEqualTo(String value) {
            addCriterion("owner_description =", value, "ownerDescription");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionNotEqualTo(String value) {
            addCriterion("owner_description <>", value, "ownerDescription");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionGreaterThan(String value) {
            addCriterion("owner_description >", value, "ownerDescription");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("owner_description >=", value, "ownerDescription");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionLessThan(String value) {
            addCriterion("owner_description <", value, "ownerDescription");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionLessThanOrEqualTo(String value) {
            addCriterion("owner_description <=", value, "ownerDescription");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionLike(String value) {
            addCriterion("owner_description like", value, "ownerDescription");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionNotLike(String value) {
            addCriterion("owner_description not like", value, "ownerDescription");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionIn(List<String> values) {
            addCriterion("owner_description in", values, "ownerDescription");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionNotIn(List<String> values) {
            addCriterion("owner_description not in", values, "ownerDescription");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionBetween(String value1, String value2) {
            addCriterion("owner_description between", value1, value2, "ownerDescription");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionNotBetween(String value1, String value2) {
            addCriterion("owner_description not between", value1, value2, "ownerDescription");
            return (Criteria) this;
        }

        public Criteria andOwnerTypeIsNull() {
            addCriterion("owner_type is null");
            return (Criteria) this;
        }

        public Criteria andOwnerTypeIsNotNull() {
            addCriterion("owner_type is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerTypeEqualTo(Integer value) {
            addCriterion("owner_type =", value, "ownerType");
            return (Criteria) this;
        }

        public Criteria andOwnerTypeNotEqualTo(Integer value) {
            addCriterion("owner_type <>", value, "ownerType");
            return (Criteria) this;
        }

        public Criteria andOwnerTypeGreaterThan(Integer value) {
            addCriterion("owner_type >", value, "ownerType");
            return (Criteria) this;
        }

        public Criteria andOwnerTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("owner_type >=", value, "ownerType");
            return (Criteria) this;
        }

        public Criteria andOwnerTypeLessThan(Integer value) {
            addCriterion("owner_type <", value, "ownerType");
            return (Criteria) this;
        }

        public Criteria andOwnerTypeLessThanOrEqualTo(Integer value) {
            addCriterion("owner_type <=", value, "ownerType");
            return (Criteria) this;
        }

        public Criteria andOwnerTypeIn(List<Integer> values) {
            addCriterion("owner_type in", values, "ownerType");
            return (Criteria) this;
        }

        public Criteria andOwnerTypeNotIn(List<Integer> values) {
            addCriterion("owner_type not in", values, "ownerType");
            return (Criteria) this;
        }

        public Criteria andOwnerTypeBetween(Integer value1, Integer value2) {
            addCriterion("owner_type between", value1, value2, "ownerType");
            return (Criteria) this;
        }

        public Criteria andOwnerTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("owner_type not between", value1, value2, "ownerType");
            return (Criteria) this;
        }

        public Criteria andOwnerLevelIsNull() {
            addCriterion("owner_level is null");
            return (Criteria) this;
        }

        public Criteria andOwnerLevelIsNotNull() {
            addCriterion("owner_level is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerLevelEqualTo(Integer value) {
            addCriterion("owner_level =", value, "ownerLevel");
            return (Criteria) this;
        }

        public Criteria andOwnerLevelNotEqualTo(Integer value) {
            addCriterion("owner_level <>", value, "ownerLevel");
            return (Criteria) this;
        }

        public Criteria andOwnerLevelGreaterThan(Integer value) {
            addCriterion("owner_level >", value, "ownerLevel");
            return (Criteria) this;
        }

        public Criteria andOwnerLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("owner_level >=", value, "ownerLevel");
            return (Criteria) this;
        }

        public Criteria andOwnerLevelLessThan(Integer value) {
            addCriterion("owner_level <", value, "ownerLevel");
            return (Criteria) this;
        }

        public Criteria andOwnerLevelLessThanOrEqualTo(Integer value) {
            addCriterion("owner_level <=", value, "ownerLevel");
            return (Criteria) this;
        }

        public Criteria andOwnerLevelIn(List<Integer> values) {
            addCriterion("owner_level in", values, "ownerLevel");
            return (Criteria) this;
        }

        public Criteria andOwnerLevelNotIn(List<Integer> values) {
            addCriterion("owner_level not in", values, "ownerLevel");
            return (Criteria) this;
        }

        public Criteria andOwnerLevelBetween(Integer value1, Integer value2) {
            addCriterion("owner_level between", value1, value2, "ownerLevel");
            return (Criteria) this;
        }

        public Criteria andOwnerLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("owner_level not between", value1, value2, "ownerLevel");
            return (Criteria) this;
        }

        public Criteria andOwnerNumberIsNull() {
            addCriterion("owner_number is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNumberIsNotNull() {
            addCriterion("owner_number is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNumberEqualTo(Integer value) {
            addCriterion("owner_number =", value, "ownerNumber");
            return (Criteria) this;
        }

        public Criteria andOwnerNumberNotEqualTo(Integer value) {
            addCriterion("owner_number <>", value, "ownerNumber");
            return (Criteria) this;
        }

        public Criteria andOwnerNumberGreaterThan(Integer value) {
            addCriterion("owner_number >", value, "ownerNumber");
            return (Criteria) this;
        }

        public Criteria andOwnerNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("owner_number >=", value, "ownerNumber");
            return (Criteria) this;
        }

        public Criteria andOwnerNumberLessThan(Integer value) {
            addCriterion("owner_number <", value, "ownerNumber");
            return (Criteria) this;
        }

        public Criteria andOwnerNumberLessThanOrEqualTo(Integer value) {
            addCriterion("owner_number <=", value, "ownerNumber");
            return (Criteria) this;
        }

        public Criteria andOwnerNumberIn(List<Integer> values) {
            addCriterion("owner_number in", values, "ownerNumber");
            return (Criteria) this;
        }

        public Criteria andOwnerNumberNotIn(List<Integer> values) {
            addCriterion("owner_number not in", values, "ownerNumber");
            return (Criteria) this;
        }

        public Criteria andOwnerNumberBetween(Integer value1, Integer value2) {
            addCriterion("owner_number between", value1, value2, "ownerNumber");
            return (Criteria) this;
        }

        public Criteria andOwnerNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("owner_number not between", value1, value2, "ownerNumber");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneIsNull() {
            addCriterion("owner_phone is null");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneIsNotNull() {
            addCriterion("owner_phone is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneEqualTo(String value) {
            addCriterion("owner_phone =", value, "ownerPhone");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneNotEqualTo(String value) {
            addCriterion("owner_phone <>", value, "ownerPhone");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneGreaterThan(String value) {
            addCriterion("owner_phone >", value, "ownerPhone");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("owner_phone >=", value, "ownerPhone");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneLessThan(String value) {
            addCriterion("owner_phone <", value, "ownerPhone");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneLessThanOrEqualTo(String value) {
            addCriterion("owner_phone <=", value, "ownerPhone");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneLike(String value) {
            addCriterion("owner_phone like", value, "ownerPhone");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneNotLike(String value) {
            addCriterion("owner_phone not like", value, "ownerPhone");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneIn(List<String> values) {
            addCriterion("owner_phone in", values, "ownerPhone");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneNotIn(List<String> values) {
            addCriterion("owner_phone not in", values, "ownerPhone");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneBetween(String value1, String value2) {
            addCriterion("owner_phone between", value1, value2, "ownerPhone");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneNotBetween(String value1, String value2) {
            addCriterion("owner_phone not between", value1, value2, "ownerPhone");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLikeInsensitive(String value) {
            addCriterion("upper(owner_name) like", value.toUpperCase(), "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerPositionLikeInsensitive(String value) {
            addCriterion("upper(owner_position) like", value.toUpperCase(), "ownerPosition");
            return (Criteria) this;
        }

        public Criteria andOwnerDescriptionLikeInsensitive(String value) {
            addCriterion("upper(owner_description) like", value.toUpperCase(), "ownerDescription");
            return (Criteria) this;
        }

        public Criteria andOwnerPhoneLikeInsensitive(String value) {
            addCriterion("upper(owner_phone) like", value.toUpperCase(), "ownerPhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_owner
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 27 18:07:00 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_owner
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}