package com.crazyclub.www.waterlab.model.mybatis;

import java.io.Serializable;
import java.util.Date;

public class Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_role.role_id
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_role.role_name
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_role.role_description
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private String roleDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_role.role_create_time
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private Date roleCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_role.role_update_time
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private Date roleUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_role.role_state
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private String roleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_role.role_id
     *
     * @return the value of wl_base_role.role_id
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_role.role_id
     *
     * @param roleId the value for wl_base_role.role_id
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_role.role_name
     *
     * @return the value of wl_base_role.role_name
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_role.role_name
     *
     * @param roleName the value for wl_base_role.role_name
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_role.role_description
     *
     * @return the value of wl_base_role.role_description
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public String getRoleDescription() {
        return roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_role.role_description
     *
     * @param roleDescription the value for wl_base_role.role_description
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription == null ? null : roleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_role.role_create_time
     *
     * @return the value of wl_base_role.role_create_time
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public Date getRoleCreateTime() {
        return roleCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_role.role_create_time
     *
     * @param roleCreateTime the value for wl_base_role.role_create_time
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setRoleCreateTime(Date roleCreateTime) {
        this.roleCreateTime = roleCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_role.role_update_time
     *
     * @return the value of wl_base_role.role_update_time
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public Date getRoleUpdateTime() {
        return roleUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_role.role_update_time
     *
     * @param roleUpdateTime the value for wl_base_role.role_update_time
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setRoleUpdateTime(Date roleUpdateTime) {
        this.roleUpdateTime = roleUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_role.role_state
     *
     * @return the value of wl_base_role.role_state
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public String getRoleState() {
        return roleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_role.role_state
     *
     * @param roleState the value for wl_base_role.role_state
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setRoleState(String roleState) {
        this.roleState = roleState == null ? null : roleState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Role other = (Role) that;
        return (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getRoleName() == null ? other.getRoleName() == null : this.getRoleName().equals(other.getRoleName()))
            && (this.getRoleDescription() == null ? other.getRoleDescription() == null : this.getRoleDescription().equals(other.getRoleDescription()))
            && (this.getRoleCreateTime() == null ? other.getRoleCreateTime() == null : this.getRoleCreateTime().equals(other.getRoleCreateTime()))
            && (this.getRoleUpdateTime() == null ? other.getRoleUpdateTime() == null : this.getRoleUpdateTime().equals(other.getRoleUpdateTime()))
            && (this.getRoleState() == null ? other.getRoleState() == null : this.getRoleState().equals(other.getRoleState()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getRoleName() == null) ? 0 : getRoleName().hashCode());
        result = prime * result + ((getRoleDescription() == null) ? 0 : getRoleDescription().hashCode());
        result = prime * result + ((getRoleCreateTime() == null) ? 0 : getRoleCreateTime().hashCode());
        result = prime * result + ((getRoleUpdateTime() == null) ? 0 : getRoleUpdateTime().hashCode());
        result = prime * result + ((getRoleState() == null) ? 0 : getRoleState().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", roleName=").append(roleName);
        sb.append(", roleDescription=").append(roleDescription);
        sb.append(", roleCreateTime=").append(roleCreateTime);
        sb.append(", roleUpdateTime=").append(roleUpdateTime);
        sb.append(", roleState=").append(roleState);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}