package com.crazyclub.www.waterlab.model.mybatis;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public RoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("role_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("role_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(Integer value) {
            addCriterion("role_id =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(Integer value) {
            addCriterion("role_id <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(Integer value) {
            addCriterion("role_id >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("role_id >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(Integer value) {
            addCriterion("role_id <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("role_id <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<Integer> values) {
            addCriterion("role_id in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<Integer> values) {
            addCriterion("role_id not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("role_id between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("role_id not between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNull() {
            addCriterion("role_name is null");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNotNull() {
            addCriterion("role_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoleNameEqualTo(String value) {
            addCriterion("role_name =", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotEqualTo(String value) {
            addCriterion("role_name <>", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThan(String value) {
            addCriterion("role_name >", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("role_name >=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThan(String value) {
            addCriterion("role_name <", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThanOrEqualTo(String value) {
            addCriterion("role_name <=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLike(String value) {
            addCriterion("role_name like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotLike(String value) {
            addCriterion("role_name not like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameIn(List<String> values) {
            addCriterion("role_name in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotIn(List<String> values) {
            addCriterion("role_name not in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameBetween(String value1, String value2) {
            addCriterion("role_name between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotBetween(String value1, String value2) {
            addCriterion("role_name not between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionIsNull() {
            addCriterion("role_description is null");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionIsNotNull() {
            addCriterion("role_description is not null");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionEqualTo(String value) {
            addCriterion("role_description =", value, "roleDescription");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionNotEqualTo(String value) {
            addCriterion("role_description <>", value, "roleDescription");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionGreaterThan(String value) {
            addCriterion("role_description >", value, "roleDescription");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("role_description >=", value, "roleDescription");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionLessThan(String value) {
            addCriterion("role_description <", value, "roleDescription");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionLessThanOrEqualTo(String value) {
            addCriterion("role_description <=", value, "roleDescription");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionLike(String value) {
            addCriterion("role_description like", value, "roleDescription");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionNotLike(String value) {
            addCriterion("role_description not like", value, "roleDescription");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionIn(List<String> values) {
            addCriterion("role_description in", values, "roleDescription");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionNotIn(List<String> values) {
            addCriterion("role_description not in", values, "roleDescription");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionBetween(String value1, String value2) {
            addCriterion("role_description between", value1, value2, "roleDescription");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionNotBetween(String value1, String value2) {
            addCriterion("role_description not between", value1, value2, "roleDescription");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeIsNull() {
            addCriterion("role_create_time is null");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeIsNotNull() {
            addCriterion("role_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeEqualTo(Date value) {
            addCriterion("role_create_time =", value, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeNotEqualTo(Date value) {
            addCriterion("role_create_time <>", value, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeGreaterThan(Date value) {
            addCriterion("role_create_time >", value, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("role_create_time >=", value, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeLessThan(Date value) {
            addCriterion("role_create_time <", value, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("role_create_time <=", value, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeIn(List<Date> values) {
            addCriterion("role_create_time in", values, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeNotIn(List<Date> values) {
            addCriterion("role_create_time not in", values, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeBetween(Date value1, Date value2) {
            addCriterion("role_create_time between", value1, value2, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("role_create_time not between", value1, value2, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleUpdateTimeIsNull() {
            addCriterion("role_update_time is null");
            return (Criteria) this;
        }

        public Criteria andRoleUpdateTimeIsNotNull() {
            addCriterion("role_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andRoleUpdateTimeEqualTo(Date value) {
            addCriterion("role_update_time =", value, "roleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleUpdateTimeNotEqualTo(Date value) {
            addCriterion("role_update_time <>", value, "roleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleUpdateTimeGreaterThan(Date value) {
            addCriterion("role_update_time >", value, "roleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("role_update_time >=", value, "roleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleUpdateTimeLessThan(Date value) {
            addCriterion("role_update_time <", value, "roleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("role_update_time <=", value, "roleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleUpdateTimeIn(List<Date> values) {
            addCriterion("role_update_time in", values, "roleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleUpdateTimeNotIn(List<Date> values) {
            addCriterion("role_update_time not in", values, "roleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("role_update_time between", value1, value2, "roleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("role_update_time not between", value1, value2, "roleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleStateIsNull() {
            addCriterion("role_state is null");
            return (Criteria) this;
        }

        public Criteria andRoleStateIsNotNull() {
            addCriterion("role_state is not null");
            return (Criteria) this;
        }

        public Criteria andRoleStateEqualTo(String value) {
            addCriterion("role_state =", value, "roleState");
            return (Criteria) this;
        }

        public Criteria andRoleStateNotEqualTo(String value) {
            addCriterion("role_state <>", value, "roleState");
            return (Criteria) this;
        }

        public Criteria andRoleStateGreaterThan(String value) {
            addCriterion("role_state >", value, "roleState");
            return (Criteria) this;
        }

        public Criteria andRoleStateGreaterThanOrEqualTo(String value) {
            addCriterion("role_state >=", value, "roleState");
            return (Criteria) this;
        }

        public Criteria andRoleStateLessThan(String value) {
            addCriterion("role_state <", value, "roleState");
            return (Criteria) this;
        }

        public Criteria andRoleStateLessThanOrEqualTo(String value) {
            addCriterion("role_state <=", value, "roleState");
            return (Criteria) this;
        }

        public Criteria andRoleStateLike(String value) {
            addCriterion("role_state like", value, "roleState");
            return (Criteria) this;
        }

        public Criteria andRoleStateNotLike(String value) {
            addCriterion("role_state not like", value, "roleState");
            return (Criteria) this;
        }

        public Criteria andRoleStateIn(List<String> values) {
            addCriterion("role_state in", values, "roleState");
            return (Criteria) this;
        }

        public Criteria andRoleStateNotIn(List<String> values) {
            addCriterion("role_state not in", values, "roleState");
            return (Criteria) this;
        }

        public Criteria andRoleStateBetween(String value1, String value2) {
            addCriterion("role_state between", value1, value2, "roleState");
            return (Criteria) this;
        }

        public Criteria andRoleStateNotBetween(String value1, String value2) {
            addCriterion("role_state not between", value1, value2, "roleState");
            return (Criteria) this;
        }

        public Criteria andRoleNameLikeInsensitive(String value) {
            addCriterion("upper(role_name) like", value.toUpperCase(), "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleDescriptionLikeInsensitive(String value) {
            addCriterion("upper(role_description) like", value.toUpperCase(), "roleDescription");
            return (Criteria) this;
        }

        public Criteria andRoleStateLikeInsensitive(String value) {
            addCriterion("upper(role_state) like", value.toUpperCase(), "roleState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_role
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 06 15:14:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_role
     *
     * @mbg.generated Tue Nov 06 15:14:10 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}