package com.crazyclub.www.waterlab.model.mybatis;

import java.util.ArrayList;
import java.util.List;

public class StandardExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public StandardExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStandardIdIsNull() {
            addCriterion("standard_id is null");
            return (Criteria) this;
        }

        public Criteria andStandardIdIsNotNull() {
            addCriterion("standard_id is not null");
            return (Criteria) this;
        }

        public Criteria andStandardIdEqualTo(Integer value) {
            addCriterion("standard_id =", value, "standardId");
            return (Criteria) this;
        }

        public Criteria andStandardIdNotEqualTo(Integer value) {
            addCriterion("standard_id <>", value, "standardId");
            return (Criteria) this;
        }

        public Criteria andStandardIdGreaterThan(Integer value) {
            addCriterion("standard_id >", value, "standardId");
            return (Criteria) this;
        }

        public Criteria andStandardIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("standard_id >=", value, "standardId");
            return (Criteria) this;
        }

        public Criteria andStandardIdLessThan(Integer value) {
            addCriterion("standard_id <", value, "standardId");
            return (Criteria) this;
        }

        public Criteria andStandardIdLessThanOrEqualTo(Integer value) {
            addCriterion("standard_id <=", value, "standardId");
            return (Criteria) this;
        }

        public Criteria andStandardIdIn(List<Integer> values) {
            addCriterion("standard_id in", values, "standardId");
            return (Criteria) this;
        }

        public Criteria andStandardIdNotIn(List<Integer> values) {
            addCriterion("standard_id not in", values, "standardId");
            return (Criteria) this;
        }

        public Criteria andStandardIdBetween(Integer value1, Integer value2) {
            addCriterion("standard_id between", value1, value2, "standardId");
            return (Criteria) this;
        }

        public Criteria andStandardIdNotBetween(Integer value1, Integer value2) {
            addCriterion("standard_id not between", value1, value2, "standardId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdIsNull() {
            addCriterion("check_type_id is null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdIsNotNull() {
            addCriterion("check_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdEqualTo(Integer value) {
            addCriterion("check_type_id =", value, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdNotEqualTo(Integer value) {
            addCriterion("check_type_id <>", value, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdGreaterThan(Integer value) {
            addCriterion("check_type_id >", value, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_type_id >=", value, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdLessThan(Integer value) {
            addCriterion("check_type_id <", value, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("check_type_id <=", value, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdIn(List<Integer> values) {
            addCriterion("check_type_id in", values, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdNotIn(List<Integer> values) {
            addCriterion("check_type_id not in", values, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("check_type_id between", value1, value2, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andCheckTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("check_type_id not between", value1, value2, "checkTypeId");
            return (Criteria) this;
        }

        public Criteria andStandardTypeIsNull() {
            addCriterion("standard_type is null");
            return (Criteria) this;
        }

        public Criteria andStandardTypeIsNotNull() {
            addCriterion("standard_type is not null");
            return (Criteria) this;
        }

        public Criteria andStandardTypeEqualTo(Integer value) {
            addCriterion("standard_type =", value, "standardType");
            return (Criteria) this;
        }

        public Criteria andStandardTypeNotEqualTo(Integer value) {
            addCriterion("standard_type <>", value, "standardType");
            return (Criteria) this;
        }

        public Criteria andStandardTypeGreaterThan(Integer value) {
            addCriterion("standard_type >", value, "standardType");
            return (Criteria) this;
        }

        public Criteria andStandardTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("standard_type >=", value, "standardType");
            return (Criteria) this;
        }

        public Criteria andStandardTypeLessThan(Integer value) {
            addCriterion("standard_type <", value, "standardType");
            return (Criteria) this;
        }

        public Criteria andStandardTypeLessThanOrEqualTo(Integer value) {
            addCriterion("standard_type <=", value, "standardType");
            return (Criteria) this;
        }

        public Criteria andStandardTypeIn(List<Integer> values) {
            addCriterion("standard_type in", values, "standardType");
            return (Criteria) this;
        }

        public Criteria andStandardTypeNotIn(List<Integer> values) {
            addCriterion("standard_type not in", values, "standardType");
            return (Criteria) this;
        }

        public Criteria andStandardTypeBetween(Integer value1, Integer value2) {
            addCriterion("standard_type between", value1, value2, "standardType");
            return (Criteria) this;
        }

        public Criteria andStandardTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("standard_type not between", value1, value2, "standardType");
            return (Criteria) this;
        }

        public Criteria andStandardValueIsNull() {
            addCriterion("standard_value is null");
            return (Criteria) this;
        }

        public Criteria andStandardValueIsNotNull() {
            addCriterion("standard_value is not null");
            return (Criteria) this;
        }

        public Criteria andStandardValueEqualTo(String value) {
            addCriterion("standard_value =", value, "standardValue");
            return (Criteria) this;
        }

        public Criteria andStandardValueNotEqualTo(String value) {
            addCriterion("standard_value <>", value, "standardValue");
            return (Criteria) this;
        }

        public Criteria andStandardValueGreaterThan(String value) {
            addCriterion("standard_value >", value, "standardValue");
            return (Criteria) this;
        }

        public Criteria andStandardValueGreaterThanOrEqualTo(String value) {
            addCriterion("standard_value >=", value, "standardValue");
            return (Criteria) this;
        }

        public Criteria andStandardValueLessThan(String value) {
            addCriterion("standard_value <", value, "standardValue");
            return (Criteria) this;
        }

        public Criteria andStandardValueLessThanOrEqualTo(String value) {
            addCriterion("standard_value <=", value, "standardValue");
            return (Criteria) this;
        }

        public Criteria andStandardValueLike(String value) {
            addCriterion("standard_value like", value, "standardValue");
            return (Criteria) this;
        }

        public Criteria andStandardValueNotLike(String value) {
            addCriterion("standard_value not like", value, "standardValue");
            return (Criteria) this;
        }

        public Criteria andStandardValueIn(List<String> values) {
            addCriterion("standard_value in", values, "standardValue");
            return (Criteria) this;
        }

        public Criteria andStandardValueNotIn(List<String> values) {
            addCriterion("standard_value not in", values, "standardValue");
            return (Criteria) this;
        }

        public Criteria andStandardValueBetween(String value1, String value2) {
            addCriterion("standard_value between", value1, value2, "standardValue");
            return (Criteria) this;
        }

        public Criteria andStandardValueNotBetween(String value1, String value2) {
            addCriterion("standard_value not between", value1, value2, "standardValue");
            return (Criteria) this;
        }

        public Criteria andStandardRelationIsNull() {
            addCriterion("standard_relation is null");
            return (Criteria) this;
        }

        public Criteria andStandardRelationIsNotNull() {
            addCriterion("standard_relation is not null");
            return (Criteria) this;
        }

        public Criteria andStandardRelationEqualTo(Integer value) {
            addCriterion("standard_relation =", value, "standardRelation");
            return (Criteria) this;
        }

        public Criteria andStandardRelationNotEqualTo(Integer value) {
            addCriterion("standard_relation <>", value, "standardRelation");
            return (Criteria) this;
        }

        public Criteria andStandardRelationGreaterThan(Integer value) {
            addCriterion("standard_relation >", value, "standardRelation");
            return (Criteria) this;
        }

        public Criteria andStandardRelationGreaterThanOrEqualTo(Integer value) {
            addCriterion("standard_relation >=", value, "standardRelation");
            return (Criteria) this;
        }

        public Criteria andStandardRelationLessThan(Integer value) {
            addCriterion("standard_relation <", value, "standardRelation");
            return (Criteria) this;
        }

        public Criteria andStandardRelationLessThanOrEqualTo(Integer value) {
            addCriterion("standard_relation <=", value, "standardRelation");
            return (Criteria) this;
        }

        public Criteria andStandardRelationIn(List<Integer> values) {
            addCriterion("standard_relation in", values, "standardRelation");
            return (Criteria) this;
        }

        public Criteria andStandardRelationNotIn(List<Integer> values) {
            addCriterion("standard_relation not in", values, "standardRelation");
            return (Criteria) this;
        }

        public Criteria andStandardRelationBetween(Integer value1, Integer value2) {
            addCriterion("standard_relation between", value1, value2, "standardRelation");
            return (Criteria) this;
        }

        public Criteria andStandardRelationNotBetween(Integer value1, Integer value2) {
            addCriterion("standard_relation not between", value1, value2, "standardRelation");
            return (Criteria) this;
        }

        public Criteria andStandardLevelIsNull() {
            addCriterion("standard_level is null");
            return (Criteria) this;
        }

        public Criteria andStandardLevelIsNotNull() {
            addCriterion("standard_level is not null");
            return (Criteria) this;
        }

        public Criteria andStandardLevelEqualTo(Integer value) {
            addCriterion("standard_level =", value, "standardLevel");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNotEqualTo(Integer value) {
            addCriterion("standard_level <>", value, "standardLevel");
            return (Criteria) this;
        }

        public Criteria andStandardLevelGreaterThan(Integer value) {
            addCriterion("standard_level >", value, "standardLevel");
            return (Criteria) this;
        }

        public Criteria andStandardLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("standard_level >=", value, "standardLevel");
            return (Criteria) this;
        }

        public Criteria andStandardLevelLessThan(Integer value) {
            addCriterion("standard_level <", value, "standardLevel");
            return (Criteria) this;
        }

        public Criteria andStandardLevelLessThanOrEqualTo(Integer value) {
            addCriterion("standard_level <=", value, "standardLevel");
            return (Criteria) this;
        }

        public Criteria andStandardLevelIn(List<Integer> values) {
            addCriterion("standard_level in", values, "standardLevel");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNotIn(List<Integer> values) {
            addCriterion("standard_level not in", values, "standardLevel");
            return (Criteria) this;
        }

        public Criteria andStandardLevelBetween(Integer value1, Integer value2) {
            addCriterion("standard_level between", value1, value2, "standardLevel");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("standard_level not between", value1, value2, "standardLevel");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameIsNull() {
            addCriterion("standard_level_name is null");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameIsNotNull() {
            addCriterion("standard_level_name is not null");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameEqualTo(String value) {
            addCriterion("standard_level_name =", value, "standardLevelName");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameNotEqualTo(String value) {
            addCriterion("standard_level_name <>", value, "standardLevelName");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameGreaterThan(String value) {
            addCriterion("standard_level_name >", value, "standardLevelName");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameGreaterThanOrEqualTo(String value) {
            addCriterion("standard_level_name >=", value, "standardLevelName");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameLessThan(String value) {
            addCriterion("standard_level_name <", value, "standardLevelName");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameLessThanOrEqualTo(String value) {
            addCriterion("standard_level_name <=", value, "standardLevelName");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameLike(String value) {
            addCriterion("standard_level_name like", value, "standardLevelName");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameNotLike(String value) {
            addCriterion("standard_level_name not like", value, "standardLevelName");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameIn(List<String> values) {
            addCriterion("standard_level_name in", values, "standardLevelName");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameNotIn(List<String> values) {
            addCriterion("standard_level_name not in", values, "standardLevelName");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameBetween(String value1, String value2) {
            addCriterion("standard_level_name between", value1, value2, "standardLevelName");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameNotBetween(String value1, String value2) {
            addCriterion("standard_level_name not between", value1, value2, "standardLevelName");
            return (Criteria) this;
        }

        public Criteria andStandardValueLikeInsensitive(String value) {
            addCriterion("upper(standard_value) like", value.toUpperCase(), "standardValue");
            return (Criteria) this;
        }

        public Criteria andStandardLevelNameLikeInsensitive(String value) {
            addCriterion("upper(standard_level_name) like", value.toUpperCase(), "standardLevelName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_standard
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 27 18:07:00 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}