package com.crazyclub.www.waterlab.model.mybatis;

import java.io.Serializable;

public class Standard implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_standard.standard_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Integer standardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_standard.check_type_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Integer checkTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_standard.standard_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Integer standardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_standard.standard_value
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String standardValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_standard.standard_relation
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Integer standardRelation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_standard.standard_level
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Integer standardLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_standard.standard_level_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String standardLevelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_standard.standard_id
     *
     * @return the value of wl_base_standard.standard_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Integer getStandardId() {
        return standardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_standard.standard_id
     *
     * @param standardId the value for wl_base_standard.standard_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setStandardId(Integer standardId) {
        this.standardId = standardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_standard.check_type_id
     *
     * @return the value of wl_base_standard.check_type_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Integer getCheckTypeId() {
        return checkTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_standard.check_type_id
     *
     * @param checkTypeId the value for wl_base_standard.check_type_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setCheckTypeId(Integer checkTypeId) {
        this.checkTypeId = checkTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_standard.standard_type
     *
     * @return the value of wl_base_standard.standard_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Integer getStandardType() {
        return standardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_standard.standard_type
     *
     * @param standardType the value for wl_base_standard.standard_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setStandardType(Integer standardType) {
        this.standardType = standardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_standard.standard_value
     *
     * @return the value of wl_base_standard.standard_value
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getStandardValue() {
        return standardValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_standard.standard_value
     *
     * @param standardValue the value for wl_base_standard.standard_value
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setStandardValue(String standardValue) {
        this.standardValue = standardValue == null ? null : standardValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_standard.standard_relation
     *
     * @return the value of wl_base_standard.standard_relation
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Integer getStandardRelation() {
        return standardRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_standard.standard_relation
     *
     * @param standardRelation the value for wl_base_standard.standard_relation
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setStandardRelation(Integer standardRelation) {
        this.standardRelation = standardRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_standard.standard_level
     *
     * @return the value of wl_base_standard.standard_level
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Integer getStandardLevel() {
        return standardLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_standard.standard_level
     *
     * @param standardLevel the value for wl_base_standard.standard_level
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setStandardLevel(Integer standardLevel) {
        this.standardLevel = standardLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_standard.standard_level_name
     *
     * @return the value of wl_base_standard.standard_level_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getStandardLevelName() {
        return standardLevelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_standard.standard_level_name
     *
     * @param standardLevelName the value for wl_base_standard.standard_level_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setStandardLevelName(String standardLevelName) {
        this.standardLevelName = standardLevelName == null ? null : standardLevelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Standard other = (Standard) that;
        return (this.getStandardId() == null ? other.getStandardId() == null : this.getStandardId().equals(other.getStandardId()))
            && (this.getCheckTypeId() == null ? other.getCheckTypeId() == null : this.getCheckTypeId().equals(other.getCheckTypeId()))
            && (this.getStandardType() == null ? other.getStandardType() == null : this.getStandardType().equals(other.getStandardType()))
            && (this.getStandardValue() == null ? other.getStandardValue() == null : this.getStandardValue().equals(other.getStandardValue()))
            && (this.getStandardRelation() == null ? other.getStandardRelation() == null : this.getStandardRelation().equals(other.getStandardRelation()))
            && (this.getStandardLevel() == null ? other.getStandardLevel() == null : this.getStandardLevel().equals(other.getStandardLevel()))
            && (this.getStandardLevelName() == null ? other.getStandardLevelName() == null : this.getStandardLevelName().equals(other.getStandardLevelName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStandardId() == null) ? 0 : getStandardId().hashCode());
        result = prime * result + ((getCheckTypeId() == null) ? 0 : getCheckTypeId().hashCode());
        result = prime * result + ((getStandardType() == null) ? 0 : getStandardType().hashCode());
        result = prime * result + ((getStandardValue() == null) ? 0 : getStandardValue().hashCode());
        result = prime * result + ((getStandardRelation() == null) ? 0 : getStandardRelation().hashCode());
        result = prime * result + ((getStandardLevel() == null) ? 0 : getStandardLevel().hashCode());
        result = prime * result + ((getStandardLevelName() == null) ? 0 : getStandardLevelName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_standard
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", standardId=").append(standardId);
        sb.append(", checkTypeId=").append(checkTypeId);
        sb.append(", standardType=").append(standardType);
        sb.append(", standardValue=").append(standardValue);
        sb.append(", standardRelation=").append(standardRelation);
        sb.append(", standardLevel=").append(standardLevel);
        sb.append(", standardLevelName=").append(standardLevelName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}