package com.crazyclub.www.waterlab.model.mybatis;

import java.util.ArrayList;
import java.util.List;

public class WaterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public WaterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWaterIdIsNull() {
            addCriterion("water_id is null");
            return (Criteria) this;
        }

        public Criteria andWaterIdIsNotNull() {
            addCriterion("water_id is not null");
            return (Criteria) this;
        }

        public Criteria andWaterIdEqualTo(Integer value) {
            addCriterion("water_id =", value, "waterId");
            return (Criteria) this;
        }

        public Criteria andWaterIdNotEqualTo(Integer value) {
            addCriterion("water_id <>", value, "waterId");
            return (Criteria) this;
        }

        public Criteria andWaterIdGreaterThan(Integer value) {
            addCriterion("water_id >", value, "waterId");
            return (Criteria) this;
        }

        public Criteria andWaterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("water_id >=", value, "waterId");
            return (Criteria) this;
        }

        public Criteria andWaterIdLessThan(Integer value) {
            addCriterion("water_id <", value, "waterId");
            return (Criteria) this;
        }

        public Criteria andWaterIdLessThanOrEqualTo(Integer value) {
            addCriterion("water_id <=", value, "waterId");
            return (Criteria) this;
        }

        public Criteria andWaterIdIn(List<Integer> values) {
            addCriterion("water_id in", values, "waterId");
            return (Criteria) this;
        }

        public Criteria andWaterIdNotIn(List<Integer> values) {
            addCriterion("water_id not in", values, "waterId");
            return (Criteria) this;
        }

        public Criteria andWaterIdBetween(Integer value1, Integer value2) {
            addCriterion("water_id between", value1, value2, "waterId");
            return (Criteria) this;
        }

        public Criteria andWaterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("water_id not between", value1, value2, "waterId");
            return (Criteria) this;
        }

        public Criteria andWaterNameIsNull() {
            addCriterion("water_name is null");
            return (Criteria) this;
        }

        public Criteria andWaterNameIsNotNull() {
            addCriterion("water_name is not null");
            return (Criteria) this;
        }

        public Criteria andWaterNameEqualTo(String value) {
            addCriterion("water_name =", value, "waterName");
            return (Criteria) this;
        }

        public Criteria andWaterNameNotEqualTo(String value) {
            addCriterion("water_name <>", value, "waterName");
            return (Criteria) this;
        }

        public Criteria andWaterNameGreaterThan(String value) {
            addCriterion("water_name >", value, "waterName");
            return (Criteria) this;
        }

        public Criteria andWaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("water_name >=", value, "waterName");
            return (Criteria) this;
        }

        public Criteria andWaterNameLessThan(String value) {
            addCriterion("water_name <", value, "waterName");
            return (Criteria) this;
        }

        public Criteria andWaterNameLessThanOrEqualTo(String value) {
            addCriterion("water_name <=", value, "waterName");
            return (Criteria) this;
        }

        public Criteria andWaterNameLike(String value) {
            addCriterion("water_name like", value, "waterName");
            return (Criteria) this;
        }

        public Criteria andWaterNameNotLike(String value) {
            addCriterion("water_name not like", value, "waterName");
            return (Criteria) this;
        }

        public Criteria andWaterNameIn(List<String> values) {
            addCriterion("water_name in", values, "waterName");
            return (Criteria) this;
        }

        public Criteria andWaterNameNotIn(List<String> values) {
            addCriterion("water_name not in", values, "waterName");
            return (Criteria) this;
        }

        public Criteria andWaterNameBetween(String value1, String value2) {
            addCriterion("water_name between", value1, value2, "waterName");
            return (Criteria) this;
        }

        public Criteria andWaterNameNotBetween(String value1, String value2) {
            addCriterion("water_name not between", value1, value2, "waterName");
            return (Criteria) this;
        }

        public Criteria andWaterLabelIsNull() {
            addCriterion("water_label is null");
            return (Criteria) this;
        }

        public Criteria andWaterLabelIsNotNull() {
            addCriterion("water_label is not null");
            return (Criteria) this;
        }

        public Criteria andWaterLabelEqualTo(String value) {
            addCriterion("water_label =", value, "waterLabel");
            return (Criteria) this;
        }

        public Criteria andWaterLabelNotEqualTo(String value) {
            addCriterion("water_label <>", value, "waterLabel");
            return (Criteria) this;
        }

        public Criteria andWaterLabelGreaterThan(String value) {
            addCriterion("water_label >", value, "waterLabel");
            return (Criteria) this;
        }

        public Criteria andWaterLabelGreaterThanOrEqualTo(String value) {
            addCriterion("water_label >=", value, "waterLabel");
            return (Criteria) this;
        }

        public Criteria andWaterLabelLessThan(String value) {
            addCriterion("water_label <", value, "waterLabel");
            return (Criteria) this;
        }

        public Criteria andWaterLabelLessThanOrEqualTo(String value) {
            addCriterion("water_label <=", value, "waterLabel");
            return (Criteria) this;
        }

        public Criteria andWaterLabelLike(String value) {
            addCriterion("water_label like", value, "waterLabel");
            return (Criteria) this;
        }

        public Criteria andWaterLabelNotLike(String value) {
            addCriterion("water_label not like", value, "waterLabel");
            return (Criteria) this;
        }

        public Criteria andWaterLabelIn(List<String> values) {
            addCriterion("water_label in", values, "waterLabel");
            return (Criteria) this;
        }

        public Criteria andWaterLabelNotIn(List<String> values) {
            addCriterion("water_label not in", values, "waterLabel");
            return (Criteria) this;
        }

        public Criteria andWaterLabelBetween(String value1, String value2) {
            addCriterion("water_label between", value1, value2, "waterLabel");
            return (Criteria) this;
        }

        public Criteria andWaterLabelNotBetween(String value1, String value2) {
            addCriterion("water_label not between", value1, value2, "waterLabel");
            return (Criteria) this;
        }

        public Criteria andWaterLevelIsNull() {
            addCriterion("water_level is null");
            return (Criteria) this;
        }

        public Criteria andWaterLevelIsNotNull() {
            addCriterion("water_level is not null");
            return (Criteria) this;
        }

        public Criteria andWaterLevelEqualTo(Integer value) {
            addCriterion("water_level =", value, "waterLevel");
            return (Criteria) this;
        }

        public Criteria andWaterLevelNotEqualTo(Integer value) {
            addCriterion("water_level <>", value, "waterLevel");
            return (Criteria) this;
        }

        public Criteria andWaterLevelGreaterThan(Integer value) {
            addCriterion("water_level >", value, "waterLevel");
            return (Criteria) this;
        }

        public Criteria andWaterLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("water_level >=", value, "waterLevel");
            return (Criteria) this;
        }

        public Criteria andWaterLevelLessThan(Integer value) {
            addCriterion("water_level <", value, "waterLevel");
            return (Criteria) this;
        }

        public Criteria andWaterLevelLessThanOrEqualTo(Integer value) {
            addCriterion("water_level <=", value, "waterLevel");
            return (Criteria) this;
        }

        public Criteria andWaterLevelIn(List<Integer> values) {
            addCriterion("water_level in", values, "waterLevel");
            return (Criteria) this;
        }

        public Criteria andWaterLevelNotIn(List<Integer> values) {
            addCriterion("water_level not in", values, "waterLevel");
            return (Criteria) this;
        }

        public Criteria andWaterLevelBetween(Integer value1, Integer value2) {
            addCriterion("water_level between", value1, value2, "waterLevel");
            return (Criteria) this;
        }

        public Criteria andWaterLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("water_level not between", value1, value2, "waterLevel");
            return (Criteria) this;
        }

        public Criteria andWaterTypeIsNull() {
            addCriterion("water_type is null");
            return (Criteria) this;
        }

        public Criteria andWaterTypeIsNotNull() {
            addCriterion("water_type is not null");
            return (Criteria) this;
        }

        public Criteria andWaterTypeEqualTo(Integer value) {
            addCriterion("water_type =", value, "waterType");
            return (Criteria) this;
        }

        public Criteria andWaterTypeNotEqualTo(Integer value) {
            addCriterion("water_type <>", value, "waterType");
            return (Criteria) this;
        }

        public Criteria andWaterTypeGreaterThan(Integer value) {
            addCriterion("water_type >", value, "waterType");
            return (Criteria) this;
        }

        public Criteria andWaterTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("water_type >=", value, "waterType");
            return (Criteria) this;
        }

        public Criteria andWaterTypeLessThan(Integer value) {
            addCriterion("water_type <", value, "waterType");
            return (Criteria) this;
        }

        public Criteria andWaterTypeLessThanOrEqualTo(Integer value) {
            addCriterion("water_type <=", value, "waterType");
            return (Criteria) this;
        }

        public Criteria andWaterTypeIn(List<Integer> values) {
            addCriterion("water_type in", values, "waterType");
            return (Criteria) this;
        }

        public Criteria andWaterTypeNotIn(List<Integer> values) {
            addCriterion("water_type not in", values, "waterType");
            return (Criteria) this;
        }

        public Criteria andWaterTypeBetween(Integer value1, Integer value2) {
            addCriterion("water_type between", value1, value2, "waterType");
            return (Criteria) this;
        }

        public Criteria andWaterTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("water_type not between", value1, value2, "waterType");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionIsNull() {
            addCriterion("water_description is null");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionIsNotNull() {
            addCriterion("water_description is not null");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionEqualTo(String value) {
            addCriterion("water_description =", value, "waterDescription");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionNotEqualTo(String value) {
            addCriterion("water_description <>", value, "waterDescription");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionGreaterThan(String value) {
            addCriterion("water_description >", value, "waterDescription");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("water_description >=", value, "waterDescription");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionLessThan(String value) {
            addCriterion("water_description <", value, "waterDescription");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionLessThanOrEqualTo(String value) {
            addCriterion("water_description <=", value, "waterDescription");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionLike(String value) {
            addCriterion("water_description like", value, "waterDescription");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionNotLike(String value) {
            addCriterion("water_description not like", value, "waterDescription");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionIn(List<String> values) {
            addCriterion("water_description in", values, "waterDescription");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionNotIn(List<String> values) {
            addCriterion("water_description not in", values, "waterDescription");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionBetween(String value1, String value2) {
            addCriterion("water_description between", value1, value2, "waterDescription");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionNotBetween(String value1, String value2) {
            addCriterion("water_description not between", value1, value2, "waterDescription");
            return (Criteria) this;
        }

        public Criteria andWaterCountryIdIsNull() {
            addCriterion("water_country_id is null");
            return (Criteria) this;
        }

        public Criteria andWaterCountryIdIsNotNull() {
            addCriterion("water_country_id is not null");
            return (Criteria) this;
        }

        public Criteria andWaterCountryIdEqualTo(Integer value) {
            addCriterion("water_country_id =", value, "waterCountryId");
            return (Criteria) this;
        }

        public Criteria andWaterCountryIdNotEqualTo(Integer value) {
            addCriterion("water_country_id <>", value, "waterCountryId");
            return (Criteria) this;
        }

        public Criteria andWaterCountryIdGreaterThan(Integer value) {
            addCriterion("water_country_id >", value, "waterCountryId");
            return (Criteria) this;
        }

        public Criteria andWaterCountryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("water_country_id >=", value, "waterCountryId");
            return (Criteria) this;
        }

        public Criteria andWaterCountryIdLessThan(Integer value) {
            addCriterion("water_country_id <", value, "waterCountryId");
            return (Criteria) this;
        }

        public Criteria andWaterCountryIdLessThanOrEqualTo(Integer value) {
            addCriterion("water_country_id <=", value, "waterCountryId");
            return (Criteria) this;
        }

        public Criteria andWaterCountryIdIn(List<Integer> values) {
            addCriterion("water_country_id in", values, "waterCountryId");
            return (Criteria) this;
        }

        public Criteria andWaterCountryIdNotIn(List<Integer> values) {
            addCriterion("water_country_id not in", values, "waterCountryId");
            return (Criteria) this;
        }

        public Criteria andWaterCountryIdBetween(Integer value1, Integer value2) {
            addCriterion("water_country_id between", value1, value2, "waterCountryId");
            return (Criteria) this;
        }

        public Criteria andWaterCountryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("water_country_id not between", value1, value2, "waterCountryId");
            return (Criteria) this;
        }

        public Criteria andWaterStandardIdIsNull() {
            addCriterion("water_standard_id is null");
            return (Criteria) this;
        }

        public Criteria andWaterStandardIdIsNotNull() {
            addCriterion("water_standard_id is not null");
            return (Criteria) this;
        }

        public Criteria andWaterStandardIdEqualTo(Integer value) {
            addCriterion("water_standard_id =", value, "waterStandardId");
            return (Criteria) this;
        }

        public Criteria andWaterStandardIdNotEqualTo(Integer value) {
            addCriterion("water_standard_id <>", value, "waterStandardId");
            return (Criteria) this;
        }

        public Criteria andWaterStandardIdGreaterThan(Integer value) {
            addCriterion("water_standard_id >", value, "waterStandardId");
            return (Criteria) this;
        }

        public Criteria andWaterStandardIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("water_standard_id >=", value, "waterStandardId");
            return (Criteria) this;
        }

        public Criteria andWaterStandardIdLessThan(Integer value) {
            addCriterion("water_standard_id <", value, "waterStandardId");
            return (Criteria) this;
        }

        public Criteria andWaterStandardIdLessThanOrEqualTo(Integer value) {
            addCriterion("water_standard_id <=", value, "waterStandardId");
            return (Criteria) this;
        }

        public Criteria andWaterStandardIdIn(List<Integer> values) {
            addCriterion("water_standard_id in", values, "waterStandardId");
            return (Criteria) this;
        }

        public Criteria andWaterStandardIdNotIn(List<Integer> values) {
            addCriterion("water_standard_id not in", values, "waterStandardId");
            return (Criteria) this;
        }

        public Criteria andWaterStandardIdBetween(Integer value1, Integer value2) {
            addCriterion("water_standard_id between", value1, value2, "waterStandardId");
            return (Criteria) this;
        }

        public Criteria andWaterStandardIdNotBetween(Integer value1, Integer value2) {
            addCriterion("water_standard_id not between", value1, value2, "waterStandardId");
            return (Criteria) this;
        }

        public Criteria andWaterNameLikeInsensitive(String value) {
            addCriterion("upper(water_name) like", value.toUpperCase(), "waterName");
            return (Criteria) this;
        }

        public Criteria andWaterLabelLikeInsensitive(String value) {
            addCriterion("upper(water_label) like", value.toUpperCase(), "waterLabel");
            return (Criteria) this;
        }

        public Criteria andWaterDescriptionLikeInsensitive(String value) {
            addCriterion("upper(water_description) like", value.toUpperCase(), "waterDescription");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_water
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 27 18:07:00 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}