package com.crazyclub.www.waterlab.model.mybatis;

import java.io.Serializable;

public class Water implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_water.water_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Integer waterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_water.water_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String waterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_water.water_label
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String waterLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_water.water_level
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Integer waterLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_water.water_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Integer waterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_water.water_description
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private String waterDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_water.water_country_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Integer waterCountryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wl_base_water.water_standard_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private Integer waterStandardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_water.water_id
     *
     * @return the value of wl_base_water.water_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Integer getWaterId() {
        return waterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_water.water_id
     *
     * @param waterId the value for wl_base_water.water_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setWaterId(Integer waterId) {
        this.waterId = waterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_water.water_name
     *
     * @return the value of wl_base_water.water_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getWaterName() {
        return waterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_water.water_name
     *
     * @param waterName the value for wl_base_water.water_name
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setWaterName(String waterName) {
        this.waterName = waterName == null ? null : waterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_water.water_label
     *
     * @return the value of wl_base_water.water_label
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getWaterLabel() {
        return waterLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_water.water_label
     *
     * @param waterLabel the value for wl_base_water.water_label
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setWaterLabel(String waterLabel) {
        this.waterLabel = waterLabel == null ? null : waterLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_water.water_level
     *
     * @return the value of wl_base_water.water_level
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Integer getWaterLevel() {
        return waterLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_water.water_level
     *
     * @param waterLevel the value for wl_base_water.water_level
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setWaterLevel(Integer waterLevel) {
        this.waterLevel = waterLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_water.water_type
     *
     * @return the value of wl_base_water.water_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Integer getWaterType() {
        return waterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_water.water_type
     *
     * @param waterType the value for wl_base_water.water_type
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setWaterType(Integer waterType) {
        this.waterType = waterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_water.water_description
     *
     * @return the value of wl_base_water.water_description
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public String getWaterDescription() {
        return waterDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_water.water_description
     *
     * @param waterDescription the value for wl_base_water.water_description
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setWaterDescription(String waterDescription) {
        this.waterDescription = waterDescription == null ? null : waterDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_water.water_country_id
     *
     * @return the value of wl_base_water.water_country_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Integer getWaterCountryId() {
        return waterCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_water.water_country_id
     *
     * @param waterCountryId the value for wl_base_water.water_country_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setWaterCountryId(Integer waterCountryId) {
        this.waterCountryId = waterCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wl_base_water.water_standard_id
     *
     * @return the value of wl_base_water.water_standard_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public Integer getWaterStandardId() {
        return waterStandardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wl_base_water.water_standard_id
     *
     * @param waterStandardId the value for wl_base_water.water_standard_id
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    public void setWaterStandardId(Integer waterStandardId) {
        this.waterStandardId = waterStandardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Water other = (Water) that;
        return (this.getWaterId() == null ? other.getWaterId() == null : this.getWaterId().equals(other.getWaterId()))
            && (this.getWaterName() == null ? other.getWaterName() == null : this.getWaterName().equals(other.getWaterName()))
            && (this.getWaterLabel() == null ? other.getWaterLabel() == null : this.getWaterLabel().equals(other.getWaterLabel()))
            && (this.getWaterLevel() == null ? other.getWaterLevel() == null : this.getWaterLevel().equals(other.getWaterLevel()))
            && (this.getWaterType() == null ? other.getWaterType() == null : this.getWaterType().equals(other.getWaterType()))
            && (this.getWaterDescription() == null ? other.getWaterDescription() == null : this.getWaterDescription().equals(other.getWaterDescription()))
            && (this.getWaterCountryId() == null ? other.getWaterCountryId() == null : this.getWaterCountryId().equals(other.getWaterCountryId()))
            && (this.getWaterStandardId() == null ? other.getWaterStandardId() == null : this.getWaterStandardId().equals(other.getWaterStandardId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getWaterId() == null) ? 0 : getWaterId().hashCode());
        result = prime * result + ((getWaterName() == null) ? 0 : getWaterName().hashCode());
        result = prime * result + ((getWaterLabel() == null) ? 0 : getWaterLabel().hashCode());
        result = prime * result + ((getWaterLevel() == null) ? 0 : getWaterLevel().hashCode());
        result = prime * result + ((getWaterType() == null) ? 0 : getWaterType().hashCode());
        result = prime * result + ((getWaterDescription() == null) ? 0 : getWaterDescription().hashCode());
        result = prime * result + ((getWaterCountryId() == null) ? 0 : getWaterCountryId().hashCode());
        result = prime * result + ((getWaterStandardId() == null) ? 0 : getWaterStandardId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wl_base_water
     *
     * @mbg.generated Tue Nov 27 18:07:00 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", waterId=").append(waterId);
        sb.append(", waterName=").append(waterName);
        sb.append(", waterLabel=").append(waterLabel);
        sb.append(", waterLevel=").append(waterLevel);
        sb.append(", waterType=").append(waterType);
        sb.append(", waterDescription=").append(waterDescription);
        sb.append(", waterCountryId=").append(waterCountryId);
        sb.append(", waterStandardId=").append(waterStandardId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}